version: '3'

volumes:
  mongodb_data:
    name: "mongodb_data"

services:
  rails:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/dev/workspace/:cached
    command: sleep infinity
    links:
      - mongo

  mongo:
    image: mongo:3.4.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
 
