version: '3'
services:
  rails:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links:
      - mongo

  mongo:
    image: mongo:3.4.0
    restart: unless-stopped
    volumes:
      - /data/db
 
